name: Deploy to Azure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main  # Trigger de workflow bij push naar de 'main' branch en bij pull requests

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy ARM template
        run: |
          az group create --name myResourceGroup --location northeurope
          az deployment group create \
            --resource-group myResourceGroup \
            --template-file .github/workflows/sql-server-template.json \
            --parameters sqlServerName=myUniqueSqlServer \
                         administratorLogin=myAdminUser \
                         administratorLoginPassword=${{ secrets.ADMIN_PASSWORD }} \
                         databaseName=myDatabase \
                         location=northeurope
